sudo: required
git:
  depth: 3
  submodules: true
env:
  matrix:
  - OS_TYPE=ubuntu OS_VERSION=18.04 OS_NAME=bionic
services:
- docker
addons:
  apt:
    update: true
before_install:
- sudo apt-get -qq update
- sudo docker pull ${OS_TYPE}:${OS_VERSION}
script:
- docker run -ti -v ${TRAVIS_BUILD_DIR}:/work:rw ${OS_TYPE}:${OS_VERSION} /bin/bash -c "cd /work; ./tests.sh ${OS_TYPE} ${OS_NAME}"
before_deploy:
- cd ${TRAVIS_BUILD_DIR}
- dpkg-deb -b tmp libomp-hermit-rs_5.0_amd64.deb
deploy:
  provider: bintray
  on:
    branch: path2rs
  skip_cleanup: true
  file: ".bintray_descriptor.json"
  key:
    secure: IMPuol32nJP+MS+R0xTC8FRR2BC5GPVjrGJDKQQTsuNFSp1KRDhqotHTEoeDWaS2s6/vfJ/CjEHQWqkh7Dg+oL1KTVg90cPIk8ha3obKx+QT3/zZT/MQfrMvrrSrAR/W/Rjh74Y+aYObYrIU74K8r3KxZWJYOk9dYyXo+yq3nWYuOUNryltTHHxBTWUodmD4/e3VgyKlxo80qQ48k+OtA0xTej3QWhFpAqVk+Y6yUZRIqXyOfMZ6iNCKT7OvQb9Hhn/guN63GIGnN6rWpvQxeWkz/h9U3Smx/Fsewzg0RLqsO/Gjk6L989wTSgDQ5FsgAG7LMG2Oywd39VG5/I8pZclsthlvVkfD1gVthgFktQFh7LStHDzgAq0rshBGnlPWvs3lFZNBvRaKm4QlPKIoqdc2K9uxNsEFazANE3bXmy3g2PWGvXWuNnXdP1AKNDkouDCnRlk4ul4vXYXQclvxFox4AVrSUmDv1EOkmyXXazerpywqe00ZCTDq8z7I1gWfqKEAdf7rMnA0IAjf6jeA5msMuCMxIcxWFYGO5guHJ+fBj8tE7WiR2ELPqiCkFErAXyjSPgEMwPX7BPDhQ+eQhbj1XQ3h/qX5VCCc4dfMyqCVBcZ2HPQjs597HXuAqfDRa6R2J4gdQbHMBXLsDUpX/5cg37IfshxgsAP/OfsZ/Vg=
  user:
    secure: vydSyB/dCo6TAcHqQ5EhSiOMXlX5Ups/SjH+CTkYXbICA1CT2jZp5F90giojQqT7q87orYPq5JViXA9XuuYHwQli5BeHrBOiRjgDwF+g0FQpn8eXD4IqbhPKK4ZIvQrzHY11o0m1tbZuYwe+BCI9mNK6Srrj2ak1uB84ZMbiy5vX+OVmh0tSerNqzApWP5FiE+ChE21GTXZYaHUZbUChrPmGDjEvsTUNmHjdbWzzQEPHoI2Agh7DZgeSNk2UaRRZ0IO42jvMELNIlm3ZbRj2PUvsbbYe/EVgKgnOXFPKY74Fnfnzs/yyx0SUaG9FqBKwEcLpUW2vZlc3TjFLxbv8wrxbggM7778NcK33XI0wWss2xHpZJ0cL0xoRPcLD+V74yUmeJElRSlY/EWAwtsUGdJUfBrSOciNbOSabKRMlEqZSormwHfQFJ6ZkOtQKaCfEx8Yz7QzSztmkkOUvDTtLJQu+NK+fZr3E+sjZr0Pl1ieYVebf0UDTk2kQXMpSW9VouoE2EBdFPR1AR07Jz8Q7xj7jLhQpL2t0EB4H4UpVpe0Wp2A7w2llyWn8QrGKV73a1N6Vkge8Lb0jOmZBAPNo72ZTj07kUVpj8j1eI8TAHaEivvzc4XlM7l+4Ip8Ht9Bm0ZHuzt5Casf3/3WmnKTJkzIkKwdODVjm7LPeq6kM6pU=
