sudo: required
git:
  depth: 3
  submodules: true
env:
  matrix:
  - OS_TYPE=debian OS_VERSION=9 OS_NAME=stretch
  - OS_TYPE=ubuntu OS_VERSION=18.04 OS_NAME=bionic
services:
- docker
addons:
  apt:
    update: true
before_install:
- sudo apt-get -qq update
- sudo docker pull ${OS_TYPE}:${OS_VERSION}
script:
- docker run -ti -v ${TRAVIS_BUILD_DIR}:/work:rw ${OS_TYPE}:${OS_VERSION} /bin/bash -c "cd /work; ./tests.sh ${OS_TYPE} ${OS_NAME}"
before_deploy:
- cd ${TRAVIS_BUILD_DIR}
- dpkg-deb -b tmp libomp-hermit_5.0-1_amd64.deb
- sed -i "s/REPLACE_REPO/$OS_TYPE/" .bintray_descriptor.json
- sed -i "s/REPLACE_OS/$OS_NAME/" .bintray_descriptor.json
deploy:
  provider: bintray
  on:
    branch: hermit
  skip_cleanup: true
  file: ".bintray_descriptor.json"
  key:
    secure: I2mhvm04v/ib0rWRANjouAthdNgHai1TWIM/aOnHIZ4nIWLaUC1RDAgR5y0eAhhVvGsCwlmhXRsR96buRruX2FuK+MbjfpmECPD3K5iuCpnhnOpLtiDyji68x2KPKq91d3ozM9njwdv+Bnvs3lHXYOFB1GFLSOqI9Egzz9znC15ra7/C1UCRSEq66IWO4iDithsEDLj7a9EcE+SyqAWSOQXKod8MTFjQpFfcPd+BQbWObwGG+8Y37sMu1Ss9Kupr9HlJ3LozzFZNp9Mcm89CE9Rz0mhxS4K0uiwnpwqONqZWIKMrAPxZBjWmdiHT2sJLaxaoqiEFukW3IPq811LrS6gIvLAw4w1E4guqo/CILO46jyDu8FOju9Qewk1DedMI8nga8H0fhBX5hIOP+nQKejF4FbwDw0gzupBMmotzG9I6TGEZZVOWkHqAuPqAok7YWX8t0V1CfLarMsrseKjtVvhvqZDZ3IHNhxyWxj/X4HXv2/ZSiDAk4FCrzJZTnoHF8wujWfVUGkut8PXVeBR0tPJnDGuuJX0+UeGb5UMfD03IP7ZvZ/Knw7ls7PrbuqQBrU2MeGwgbqHoSxpZtq7a8RkNViP65L6KkCMDlZYfdqdfZ6YnqzEbi3hWt+hD7NDak04IXb3Jxi/IRTuHHKtk2B/onUWkS12yfRFz6Ao+N98=
  user:
    secure: R23SLodKFxictTtF/WWHNqn2YS1BOctPD0CvcE5YfdeQ3Et0/bJle0GcC9gGdeDQ13olRa1dQkrD4FA3rpHJ0sVJjRyWnsLtTe03trrpnXY0R7Mji56qdXEDUhHTxRbm017ze4vAM8CeTbRc2kTeIpgJhUE/MXsj8WNxu//IaUBOtjv7RSZ7AhUN03VeOyaZUBbiqyfShXcCSDQE2ruoY9yRP8wCtbdyv33euD/J48VlQVyopAeGbYWrZ7PScxb2fbHitzRrgbVZCQpSop3POBCvxhvd1b69QpwEid096vLCveqM3+gqb2Ac4BONQiS9NDrLhaTxHLTU24pTcms/csTj5Fxen97/1jNZ0/3GgzGq5Tpx8hOdDW9A7XZ5DyhzqGvzDuC4IwdBAkKJiKcYgod0hrVDUAV/SuW8WazUVciuXey3z57HLQRvgJ0DAs8zVwmQCTmX/GlsESo7SeKtJVO1jG3PjzPToVwLCH0t/tGoOnPTCQ0RUD0oj7uO5ajT9+99M432X4tw0LaarK8lVZ5ZJwXwdOvFtekS63gInYnFfV2pQKcD2Cjnkho65iEFCldvTq2PR4Ft1RRASvDKpSVSt6JBBCArL4Knvzg2Gz+Obfd8uLeB/nCh/3Uhx7tFoCArewb28VRj/8ws83JcesKPI646cNozh1o1FImCc+4=
